server:
   port: 8080

spring:
  datasource:
     url: jdbc:postgresql://192.168.1.150:5432/hrms
     username: postgres
     password: Karcan*

  jpa:
     properties:
       hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

       javax:
         persistence:
           validation:
             mode: none
     hibernate:
       ddl-auto: validate
       show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: vhelsing3347@gmail.com
    password: 1234567Qq!
    properties:
       mail:
         smtp:
           auth: true
           starttls: 
             enable: true
cloudinary:
  api-key: 975632161177458
  secret: N6E2J8XugNgY7aWgJYxaqR50jTE
  cloud-name: doljmeipy
